"""making sure

Revision ID: 5abbf091f559
Revises: 19733e58ae30
Create Date: 2021-05-04 18:53:18.084221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5abbf091f559'
down_revision = '19733e58ae30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('tags', sa.Column('tagTypeId', sa.Integer(), nullable=False))
    op.alter_column('tags', 'postingId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('tags_tagId_fkey', 'tags', type_='foreignkey')
    op.create_foreign_key(None, 'tags', 'tagTypes', ['tagTypeId'], ['id'])
    op.drop_column('tags', 'tagId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('tagId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.create_foreign_key('tags_tagId_fkey', 'tags', 'tagTypes', ['tagId'], ['id'])
    op.alter_column('tags', 'postingId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('tags', 'tagTypeId')
    op.drop_column('tags', 'id')
    # ### end Alembic commands ###
