"""set up the tables

Revision ID: ca9bfd9b8bc7
Revises: dbe0fba0ebf9
Create Date: 2021-05-04 14:17:00.490154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca9bfd9b8bc7'
down_revision = 'dbe0fba0ebf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildingTypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tagTypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=False),
    sa.Column('buildingType', sa.Integer(), nullable=False),
    sa.Column('numGuests', sa.Integer(), nullable=False),
    sa.Column('numBeds', sa.Integer(), nullable=False),
    sa.Column('numBathrooms', sa.Integer(), nullable=False),
    sa.Column('mainImageUrl', sa.String(length=250), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['buildingType'], ['buildingTypes.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userReviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('reviewerId', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['reviewerId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('postingId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['postingId'], ['postings.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postingId', sa.Integer(), nullable=False),
    sa.Column('imageUrl', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['postingId'], ['postings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postingReviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postingId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['postingId'], ['postings.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('postingId', sa.Integer(), nullable=True),
    sa.Column('tagId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['postingId'], ['postings.id'], ),
    sa.ForeignKeyConstraint(['tagId'], ['tagTypes.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_table('postingReviews')
    op.drop_table('images')
    op.drop_table('bookings')
    op.drop_table('userReviews')
    op.drop_table('postings')
    op.drop_table('tagTypes')
    op.drop_table('buildingTypes')
    # ### end Alembic commands ###
